AWSTemplateFormatVersion: "2010-09-09"
Description: "((SO0056)) - fraud-detection-using-machine-learning demo stack"
Parameters:
  SolutionPrefix:
    Description: The name of the prefix for the solution used for naming resources.
    Type: String
  SolutionsBucket:
    Description: The bucket that contains the solution files.
    Type: String
  SolutionName:
    Type: String
  ExecutionRoleArn:
    Description: The role used when invoking the enpoint.
    Type: String

Mappings:
  RegionMap:
    "ap-southeast-2":
      "XGBoost":  "783357654285.dkr.ecr.ap-southeast-2.amazonaws.com"

Resources:
  FraudClassificationModel:
    Type: "AWS::SageMaker::Model"
    Properties:
      ExecutionRoleArn: !Ref ExecutionRoleArn
      PrimaryContainer:
        Image: !Sub
          - "${ContainerLocation}/sagemaker-xgboost:0.90-2-cpu-py3"
          - ContainerLocation:
              Fn::FindInMap: [RegionMap, !Ref "AWS::Region", "XGBoost"]
        ModelDataUrl: !Sub "s3://${SolutionsBucket}/${SolutionName}/artifacts/xgboost-model.tar.gz"
      ModelName: !Sub "${SolutionPrefix}-demo"
  FraudClassificationEndpointConfig:
    Type: "AWS::SageMaker::EndpointConfig"
    Properties:
      ProductionVariants:
        - InitialInstanceCount: 1
          InitialVariantWeight: 1.0
          InstanceType: ml.m5.xlarge
          ModelName: !GetAtt FraudClassificationModel.ModelName
          VariantName: !GetAtt FraudClassificationModel.ModelName
      EndpointConfigName: !Sub "${SolutionPrefix}-demo"
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W1200
            reason: Demo endpoint not given a KmsID
  FraudClassificationEndpoint:
    Type: "AWS::SageMaker::Endpoint"
    Properties:
      EndpointName: !Sub "${SolutionPrefix}-demo"
      EndpointConfigName: !GetAtt FraudClassificationEndpointConfig.EndpointConfigName

Outputs:
  EndpointName:
    Description: Name of the demo XGBoost fraud classification endpoint
    Value: !GetAtt FraudClassificationEndpoint.EndpointName